### PR TITLE
added search and match

### PR DESCRIPTION
**Pull request by mustafaqazi916**

### CODE REVIEW

**Review by mustafaqazi916 — COMMENTED** [review]
change

**Review by gokris165 — APPROVED** [review]

**Review by gokris165 — COMMENTED** [review]
Great stuff

**Review by louisQnt — APPROVED** [review]

**Review by mustafaqazi916 — COMMENTED** [review]
approved

**Review by jawes123 — APPROVED** [review]

**Review by jawes123 — APPROVED** [review]

**Review by jawes123 — APPROVED** [review]

**Comment by gokris165** [comment]
This commit is no longer required.

**Pull request closed without merging**
